import React from "react";
import Footer from "../../src/components/footer";
import Header from "../../src/components/header";
import styles from "./privacy-policy.module.scss";



const privacyPolicy = () => {
  return (
    <>
      <Header />
      <h1 className={styles.heading}>PRIVACY POLICY</h1>
      <div className={styles.pc}>
        <div>
          {/* Hello world */}
          <p><span style={{ fontWeight: 400 }}>THIS PRIVACY POLICY APPLIES BETWEEN YOU, THE USER OF THIS WEBSITE AND BARADIEL , THE OWNER AND PROVIDER OF THIS WEBSITE (BINGEMEEE.COM). BARADIEL TAKES THE PRIVACY OF YOUR INFORMATION VERY SERIOUSLY.</span></p>
          <p><span style={{ fontWeight: 400 }}>OUR PRIVACY POLICY EXPLAINS HOW AND BARADIEL (BINGEMEEE.COM) AND SOME OF THE COMPANIES WE WORK WITH COLLECT, USE, SHARE AND PROTECT THE INFORMATION IN RELATION TO BINGEMEEE PRODUCTS, SOFTWARE, OR SERVICES PROVIDED TO YOU ON, FROM, OR THROUGH THE BINGEMEEE WEBSITE (COLLECTIVELY, THE “SERVICE”), AND YOUR CHOICES ABOUT THE COLLECTION AND USE OF YOUR INFORMATION.</span></p>
          <p><span style={{ fontWeight: 400 }}>BY USING OUR SERVICES, YOU UNDERSTAND AND AGREE THAT WE ARE PROVIDING A PLATFORM FOR YOU TO POST CONTENT, INCLUDING DATA, TEXT, FILES, INFORMATION, USERNAMES, IMAGES, GRAPHICS, PHOTOS, PROFILES, AUDIO AND VIDEO CLIPS, SOUNDS, MUSICAL WORKS, WORKS OF AUTHORSHIP, APPLICATIONS, LINKS AND OTHER CONTENT OR MATERIALS (COLLECTIVELY, "CONTENT"), TO THE SERVICE AND TO SHARE YOUR CONTENT PUBLICLY.</span></p>
          <p><span style={{ fontWeight: 400 }}>THIS MEANS THAT OTHER USERS MAY SEARCH FOR, SEE, USE, OR SHARE ANY OF YOUR USER CONTENT THAT YOU MAKE PUBLICLY AVAILABLE THROUGH THE SERVICE, CONSISTENT WITH THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY AND OUR TERMS AND CONDITIONS.</span></p>
          <p><span style={{ fontWeight: 400 }}>OUR POLICY APPLIES TO ALL VISITORS, USERS, AND OTHERS WHO ACCESS THE SERVICE ("</span><strong>USERS</strong><span style={{ fontWeight: 400 }}>").</span></p>
          <p><strong>INFORMATION WE COLLECT:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>INFORMATION YOU PROVIDE US DIRECTLY:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR USERNAME, PASSWORD AND E-MAIL ADDRESS WHEN YOU REGISTER FOR A BINGEMEEE ACCOUNT.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR CONTENT (E.G., IMAGES, GRAPHICS, PHOTOS, PROFILES, AUDIO AND VIDEO CLIPS, SOUNDS, MUSICAL WORKS, WORKS OF AUTHORSHIP, AND OTHER CONTENT OR MATERIALS) THAT YOU POST TO THE SERVICE.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>COMMUNICATIONS BETWEEN YOU AND BINGEMEEE. FOR EXAMPLE, WE MAY SEND YOU SERVICE-RELATED EMAILS (E.G., ACCOUNT VERIFICATION, CHANGES/UPDATES TO FEATURES OF THE SERVICE, TECHNICAL, NEWS AND INFORMATION, AND SECURITY NOTICES). NOTE THAT YOU MAY NOT OPT-OUT OF SERVICE-RELATED E-MAILS.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF YOU CHOOSE TO OPEN A CREATOR ACCOUNT (AS OPPOSED TO A STANDARD USER ACCOUNT), YOU WILL ADDITIONALLY PROVIDE TO BINGEMEEE:</span></li>
            <ul>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>PROFILE INFORMATION THAT YOU PROVIDE FOR YOUR USER PROFILE. THIS INFORMATION ALLOWS US TO HELP YOU OR OTHERS BE "FOUND" ON BINGEMEEE.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF YOU CHOOSE TO POST SEXUALLY EXPLICIT CONTENT, THEN YOU WILL ADDITIONALLY PROVIDE TO BINGEMEEE:</span></li>
              <ul>
                <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR FULL NAME, INCLUDING ANY STAGE NAMES OR PRIOR NAMES;</span></li>
                <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR POSTAL ADDRESS;</span></li>
                <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR DATE OF BIRTH;</span></li>
                <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>A COPY OF YOUR OFFICIAL GOVERNMENT PHOTO ID; AND</span></li>
              </ul>
            </ul>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>ANALYTICS INFORMATION:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE USE THIRD-PARTY ANALYTICS TOOLS TO HELP US MEASURE TRAFFIC AND USAGE TRENDS FOR THE SERVICE. THESE TOOLS COLLECT INFORMATION SENT BY YOUR DEVICE OR OUR SERVICE, INCLUDING THE WEB PAGES YOU VISIT, ADD-ONS, AND OTHER INFORMATION THAT ASSISTS US IN IMPROVING THE SERVICE. WE COLLECT AND USE THIS ANALYTICS INFORMATION WITH ANALYTICS INFORMATION FROM OTHER USERS SO THAT IT CANNOT REASONABLY BE USED TO IDENTIFY ANY PARTICULAR INDIVIDUAL USER.</span></li>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>COOKIES AND SIMILAR TECHNOLOGIES:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WHEN YOU VISIT THE WEBSITE, WE MAY USE COOKIES AND SIMILAR TECHNOLOGIES LIKE PIXELS, WEB BEACONS, AND LOCAL STORAGE TO COLLECT INFORMATION ABOUT HOW YOU USE BINGEMEEE AND PROVIDE FEATURES TO YOU.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THIS WEBSITE MAY PLACE AND ACCESS CERTAIN COOKIES ON YOUR COMPUTER. BARADIEL-S USES COOKIES TO IMPROVE YOUR EXPERIENCE OF USING THE WEBSITE AND TO IMPROVE OUR RANGE OF PRODUCTS AND SERVICES. BARADIEL-S HAS CAREFULLY CHOSEN THESE COOKIES AND HAS TAKEN STEPS TO ENSURE THAT YOUR PRIVACY IS PROTECTED AND RESPECTED AT ALL TIMES.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>ALL COOKIES USED BY THIS WEBSITE ARE USED IN ACCORDANCE WITH CURRENT UK AND EU COOKIE LAW.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BEFORE THE WEBSITE PLACES COOKIES ON YOUR COMPUTER, YOU WILL BE PRESENTED WITH A MESSAGE BAR REQUESTING YOUR CONSENT TO SET THOSE COOKIES. BY GIVING YOUR CONSENT TO THE PLACING OF COOKIES, YOU ARE ENABLING BARADIEL-S TO PROVIDE A BETTER EXPERIENCE AND SERVICE TO YOU. YOU MAY, IF YOU WISH, DENY CONSENT TO THE PLACING OF COOKIES; HOWEVER CERTAIN FEATURES OF THE WEBSITE MAY NOT FUNCTION FULLY OR AS INTENDED.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THIS WEBSITE MAY PLACE THE FOLLOWING COOKIES:</span></li>
          </ul>
          <table>
            <tbody>
              <tr>
                <td>
                  <p><strong>TYPE OF COOKIE</strong></p>
                </td>
                <td>
                  <p><strong>PURPOSE</strong></p>
                </td>
              </tr>
              <tr>
                <td>
                  <p><span style={{ fontWeight: 400 }}>STRICTLY NECESSARY COOKIES</span></p>
                </td>
                <td>
                  <p><span style={{ fontWeight: 400 }}>THESE ARE COOKIES THAT ARE REQUIRED FOR THE OPERATION OF OUR WEBSITE. THEY INCLUDE, FOR EXAMPLE, COOKIES THAT ENABLE YOU TO LOG INTO SECURE AREAS OF OUR WEBSITE, USE A SHOPPING CART OR MAKE USE OF E-BILLING SERVICES.</span></p>
                </td>
              </tr>
              <tr>
                <td>
                  <p><span style={{ fontWeight: 400 }}>ANALYTICAL/PERFORMANCE COOKIES</span></p>
                </td>
                <td>
                  <p><span style={{ fontWeight: 400 }}>THEY ALLOW US TO RECOGNISE AND COUNT THE NUMBER OF VISITORS AND TO SEE HOW VISITORS MOVE AROUND OUR WEBSITE WHEN THEY ARE USING IT. THIS HELPS US TO IMPROVE THE WAY OUR WEBSITE WORKS, FOR EXAMPLE, BY ENSURING THAT USERS ARE FINDING WHAT THEY ARE LOOKING FOR EASILY.</span></p>
                </td>
              </tr>
              <tr>
                <td>
                  <p><span style={{ fontWeight: 400 }}>FUNCTIONALITY COOKIES</span></p>
                </td>
                <td>
                  <p><span style={{ fontWeight: 400 }}>THESE ARE USED TO RECOGNISE YOU WHEN YOU RETURN TO OUR WEBSITE. THIS ENABLES US TO PERSONALISE OUR CONTENT FOR YOU, GREET YOU BY NAME AND REMEMBER YOUR PREFERENCES (FOR EXAMPLE, YOUR CHOICE OF LANGUAGE OR REGION).</span></p>
                </td>
              </tr>
              <tr>
                <td>
                  <p><span style={{ fontWeight: 400 }}>TARGETING COOKIES</span></p>
                </td>
                <td>
                  <p><span style={{ fontWeight: 400 }}>THESE COOKIES RECORD YOUR VISIT TO OUR WEBSITE, THE PAGES YOU HAVE VISITED AND THE LINKS YOU HAVE FOLLOWED. WE WILL USE THIS INFORMATION TO MAKE OUR WEBSITE AND THE ADVERTISING DISPLAYED ON IT MORE RELEVANT TO YOUR INTERESTS. WE MAY ALSO SHARE THIS INFORMATION WITH THIRD PARTIES FOR THIS PURPOSE.</span></p>
                </td>
              </tr>
            </tbody>
          </table>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOU CAN FIND A LIST OF COOKIES THAT WE USE IN THE COOKIES SCHEDULE.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOU CAN CHOOSE TO ENABLE OR DISABLE COOKIES IN YOUR INTERNET BROWSER. BY DEFAULT, MOST INTERNET BROWSERS ACCEPT COOKIES, BUT THIS CAN BE CHANGED. FOR FURTHER DETAILS, PLEASE CONSULT THE HELP MENU IN YOUR INTERNET BROWSER.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOU CAN CHOOSE TO DELETE COOKIES AT ANY TIME; HOWEVER, YOU MAY LOSE ANY INFORMATION THAT ENABLES YOU TO ACCESS THE WEBSITE MORE QUICKLY AND EFFICIENTLY INCLUDING, BUT NOT LIMITED TO, PERSONALISATION SETTINGS.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IT IS RECOMMENDED THAT YOU ENSURE THAT YOUR INTERNET BROWSER IS UP-TO-DATE AND THAT YOU CONSULT THE HELP AND GUIDANCE PROVIDED BY THE DEVELOPER OF YOUR INTERNET BROWSER IF YOU ARE UNSURE ABOUT ADJUSTING YOUR PRIVACY SETTINGS.</span></li>
          </ul>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>FOR MORE INFORMATION GENERALLY ON COOKIES, INCLUDING HOW TO DISABLE THEM, PLEASE REFER TO ABOUTCOOKIES.ORG. YOU WILL ALSO FIND DETAILS ON HOW TO DELETE COOKIES FROM YOUR COMPUTER.,</span></li>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>LOGFILE INFORMATION:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>LOGFILELOGFILE INFORMATION IS AUTOMATICALLY REPORTED BY YOUR BROWSER EACH TIME YOU MAKE A REQUEST TO ACCESS (I.E., VISIT) A WEB PAGE. IT CAN ALSO BE PROVIDED WHEN THE CONTENT OF THE WEBPAGE IS DOWNLOADED TO YOUR BROWSER OR DEVICE.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WHEN YOU USE OUR SERVICE, OUR SERVERS AUTOMATICALLY RECORD CERTAIN LOG FILE INFORMATION, INCLUDING YOUR WEB REQUEST, INTERNET PROTOCOL ("IP") ADDRESS, BROWSER TYPE, REFERRING / EXIT PAGES AND URLS, NUMBER OF CLICKS AND HOW YOU INTERACT WITH LINKS ON THE SERVICE, DOMAIN NAMES, LANDING PAGES, PAGES VIEWED, AND OTHER SUCH INFORMATION. WE MAY ALSO COLLECT SIMILAR INFORMATION FROM EMAILS SENT TO OUR USERS, WHICH THEN HELP US TRACK WHICH EMAILS ARE OPENED AND WHICH RECIPIENTS CLICK LINKS. THE INFORMATION ALLOWS FOR MORE ACCURATE REPORTING AND IMPROVEMENT OF THE SERVICE.</span></li>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>METADATA:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>METADATA IS DATA THAT IS ASSOCIATED WITH YOUR CONTENT. FOR EXAMPLE, METADATA CAN DESCRIBE HOW, WHEN AND BY WHOM A PIECE OF YOUR CONTENT WAS COLLECTED AND HOW THAT CONTENT IS FORMATTED.</span></li>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>FINANCIAL INFORMATION:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE WILL NOT COLLECT FROM YOU, AND YOU WILL NOT PROVIDE ANY FINANCIAL INFORMATION TO BINGEMEEE. IF YOU WISH TO PURCHASE ANY CONTENT FROM BINGEMEEE OR OTHERWISE ACCESS FINANCIAL ASPECTS OF YOUR ACCOUNT, YOU WILL PROVIDE FINANCIAL INFORMATION TO OUR CHOSEN PARTNERS. THESE PARTNERS MAY OR MAY NOT BE LOCATED IN THE EUROPEAN ECONOMIC AREA. YOU SHOULD REVIEW ANY PRIVACY POLICY OF THESE PARTNERS PRIOR TO PROVIDING THEM WITH ANY OF YOUR PERSONAL INFORMATION.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF A CREATOR ACCOUNT WISHES TO WITHDRAW MONEY FROM THEIR BINGEMEEE ACCOUNT, THE CREATOR CAN CHOOSE TO HAVE THAT ACCOMPLISHED THROUGH A BANK TRANSFER. IF A BANK TRANSFER IS REQUESTED, THE USER WILL BE REQUIRED TO PROVIDE THE BANKING INFORMATION NECESSARY TO COMPLETE THIS TRANSFER. THIS BANKING INFORMATION IS NOT USED BY BINGEMEEE FOR ANY PURPOSES OTHER THAN COMPLETING THIS TRANSFER REQUEST.</span></li>
          </ul>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>DO NOT PROVIDE SPECIAL CATEGORIES OF PERSONAL DATA:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE ASKS YOU NOT TO SEND OR DISCLOSE THROUGH YOUR INTERACTION WITH OTHERS AND “SPECIAL CATEGORIES OF PERSONAL DATA” AS DEFINED IN THE GDPR (INFORMATION RELATED TO RACIAL OR ETHNIC ORIGIN, POLITICAL OPINIONS, RELIGIOUS OR PHYSIOLOGICAL BELIEFS, HEALTH, BIOMETRIC OR GENETIC CHARACTERISTICS, CRIMINAL BACKGROUND OR TRADE UNION MEMBERSHIP, OR DATA CONCERNING DATA SUBJECT’S SEX LIFE OR SEXUAL ORIENTATION). FOR BINGEMEEE USERS WHO ARE EU RESIDENTS, SHOULD YOU PROVIDE “SPECIAL CATEGORIES OF PERSONAL DATA” USING THE SERVICE, YOU UNDERSTAND THAT YOU HAVE EXPRESSLY CONSENTED TO THE COLLECTION, USE, AND DISCLOSURE OF SUCH DATA IN ACCORDANCE WITH THIS PRIVACY POLICY.</span></li>
          </ul>
          <p><strong>HOW WE USE YOUR INFORMATION:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IN ADDITION TO SOME OF THE SPECIFIC USES OF INFORMATION WE DESCRIBE IN THIS PRIVACY POLICY, WE MAY USE INFORMATION THAT WE RECEIVE TO:</span></li>
          </ol>
          <ul>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>VERIFY YOUR IDENTITY AT USER LOGIN;</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>REMEMBER INFORMATION SO YOU WILL NOT HAVE TO RE-ENTER IT DURING YOUR VISIT OR THE NEXT TIME YOU VISIT THE SERVICE;</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>COMMUNICATE WITH YOU VIA EMAIL TO SEND A WELCOME EMAIL, ASSIST WITH PASSWORD RECOVERY, PROVIDE AUTOMATED SYSTEM EMAILS, AND PROVIDE NEWS OR OTHER INFORMATION ABOUT THE SERVICE;</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>PROVIDE, IMPROVE, TEST, AND MONITOR THE EFFECTIVENESS OF OUR SERVICE;</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>DEVELOP AND TEST NEW PRODUCTS AND FEATURES;</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>MONITOR METRICS SUCH AS TOTAL NUMBER OF VISITORS, TRAFFIC, AND DEMOGRAPHIC PATTERNS; AND</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>DIAGNOSE OR FIX TECHNOLOGY PROBLEMS.</span></li>
          </ul>
          <p><strong>SHARING OF YOUR INFORMATION:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE WILL NOT RENT, SELL, OR SHARE YOUR INFORMATION WITH THIRD PARTIES OUTSIDE BINGEMEEE, INCLUDING MARKETING AND ADVERTISING COMPANIES, WITHOUT YOUR CONSENT.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE ALSO MAY SHARE YOUR INFORMATION AS WELL AS INFORMATION FROM TOOLS LIKE COOKIES, LOG FILES, AND DEVICE IDENTIFIERS AND LOCATION DATA, WITH THIRD-PARTY ORGANISATIONS THAT HELP US PROVIDE THE SERVICE TO YOU ("SERVICE PROVIDERS"). OUR SERVICE PROVIDERS WILL BE GIVEN ACCESS TO YOUR INFORMATION AS IS REASONABLY NECESSARY TO PROVIDE THE SERVICE UNDER REASONABLE CONFIDENTIALITY TERMS.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE MAY REMOVE PARTS OF DATA THAT CAN IDENTIFY YOU AND SHARE ANONYMISED DATA WITH OTHER PARTIES. WE MAY ALSO COMBINE YOUR INFORMATION WITH ADDITIONAL INFORMATION IN A WAY THAT IT IS NO LONGER ASSOCIATED WITH YOU AND SHARE THAT AGGREGATED INFORMATION.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>ANY INFORMATION OR CONTENT THAT YOU VOLUNTARILY DISCLOSE FOR POSTING TO THE SERVICE, SUCH AS YOUR CONTENT, BECOMES AVAILABLE TO THE PUBLIC AND OTHER USERS OF BINGEMEEE.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>SUPPOSE YOU REMOVE INFORMATION THAT YOU POSTED TO THE SERVICE. IN THAT CASE, COPIES MAY REMAIN VIEWABLE IN CACHED AND ARCHIVED PAGES OF THE SERVICE, OR IF OTHER USERS OR THIRD PARTIES USING THE SERVICE HAVE COPIED OR SAVED THAT INFORMATION.</span></li>
          </ol>
          <p><strong>WHAT HAPPENS IN THE EVENT OF A CHANGE OF CONTROL:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF WE SELL OR OTHERWISE TRANSFER PART OR THE WHOLE OF BINGEMEEE OR OUR ASSETS TO ANOTHER ORGANISATION (E.G., IN THE COURSE OF A TRANSACTION LIKE A MERGER, ACQUISITION, BANKRUPTCY, DISSOLUTION, LIQUIDATION), YOUR INFORMATION SUCH AS NAME AND EMAIL ADDRESS, YOUR CONTENT AND ANY OTHER INFORMATION COLLECTED THROUGH THE SERVICE MAY BE AMONG THE ITEMS SOLD OR TRANSFERRED. YOU WILL CONTINUE TO OWN YOUR CONTENT. THE BUYER OR TRANSFEREE WILL HAVE TO HONOUR THE COMMITMENTS WE HAVE MADE IN THIS PRIVACY POLICY.</span></li>
          </ol>
          <p><strong>RESPONDING TO LEGAL REQUESTS AND PREVENTING HARM:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE MAY ACCESS, PRESERVE AND SHARE YOUR INFORMATION IN RESPONSE TO A LEGAL REQUEST (LIKE A SEARCH WARRANT, COURT ORDER OR SUBPOENA) IF WE HAVE A GOOD FAITH BELIEF THAT THE LAW REQUIRES US TO DO SO. THIS MAY INCLUDE RESPONDING TO LEGAL REQUESTS FROM JURISDICTIONS OUTSIDE OF CHENNAI, WHERE WE HAVE A GOOD FAITH BELIEF THAT THE RESPONSE IS REQUIRED BY LAW IN THAT JURISDICTION, AFFECTS USERS IN THAT JURISDICTION, AND IS CONSISTENT WITH INTERNATIONALLY RECOGNISED STANDARDS. WE MAY ALSO ACCESS, PRESERVE AND SHARE INFORMATION WHEN WE HAVE A GOOD FAITH BELIEF IT IS NECESSARY TO: DETECT, PREVENT AND ADDRESS FRAUD AND OTHER ILLEGAL ACTIVITY; TO PROTECT OURSELVES, YOU AND OTHERS, INCLUDING AS PART OF INVESTIGATIONS; AND TO PREVENT DEATH OR IMMINENT BODILY HARM. INFORMATION WE RECEIVE ABOUT YOU MAY BE ACCESSED, PROCESSED AND RETAINED FOR AN EXTENDED PERIOD OF TIME WHEN IT IS THE SUBJECT OF A LEGAL REQUEST OR OBLIGATION, GOVERNMENTAL INVESTIGATION, OR INVESTIGATIONS CONCERNING POSSIBLE VIOLATIONS OF OUR TERMS OR POLICIES, OR OTHERWISE TO PREVENT HARM.</span></li>
          </ol>
          <p><strong>HOW WE STORE YOUR INFORMATION:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR INFORMATION COLLECTED THROUGH THE SERVICE MAY BE STORED AND PROCESSED IN CHENNAI OR ANY OTHER COUNTRY IN WHICH BINGEMEEE OR SERVICE PROVIDERS MAINTAIN FACILITIES.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE OR SERVICE PROVIDERS MAY TRANSFER INFORMATION THAT WE COLLECT ABOUT YOU, INCLUDING PERSONAL INFORMATION ACROSS BORDERS AND FROM YOUR COUNTRY OR JURISDICTION, TO OTHER COUNTRIES OR JURISDICTIONS WORLDWIDE. IF YOU ARE LOCATED IN THE UNITED STATES OR OTHER REGIONS WITH LAWS GOVERNING DATA COLLECTION AND USE THAT MAY DIFFER FROM EU LAW, PLEASE NOTE THAT WE MAY TRANSFER INFORMATION, INCLUDING PERSONAL INFORMATION, TO A COUNTRY AND JURISDICTION THAT DOES NOT HAVE THE SAME DATA PROTECTION LAWS AS YOUR JURISDICTION.,</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BY REGISTERING FOR AND USING THE SERVICE, YOU CONSENT TO THE TRANSFER OF INFORMATION TO CHENNAI OR ANY OTHER COUNTRY IN WHICH BINGEMEEE OR SERVICE PROVIDERS MAINTAIN FACILITIES AND THE USE AND DISCLOSURE OF INFORMATION ABOUT YOU AS DESCRIBED IN THIS PRIVACY POLICY.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE USE COMMERCIALLY REASONABLE SAFEGUARDS TO HELP KEEP THE INFORMATION COLLECTED THROUGH THE SERVICE SECURE AND TAKE REASONABLE STEPS (SUCH AS REQUESTING A UNIQUE PASSWORD) TO VERIFY YOUR IDENTITY BEFORE GRANTING YOU ACCESS TO YOUR ACCOUNT. HOWEVER, BINGEMEEE CANNOT ENSURE THE SECURITY OF ANY INFORMATION YOU TRANSMIT TO BINGEMEEE OR GUARANTEE THAT INFORMATION ON THE SERVICE MAY NOT BE ACCESSED, DISCLOSED, ALTERED, OR DESTROYED. IN THE EVENT THAT ANY PERSONAL INFORMATION IN OUR POSSESSION OR UNDER OUR CONTROL IS COMPROMISED AS A RESULT OF A SECURITY BREACH, WE WILL TAKE REASONABLE STEPS TO INVESTIGATE THE SITUATION AND, WHERE APPROPRIATE, NOTIFY THOSE INDIVIDUALS WHOSE INFORMATION MAY HAVE BEEN COMPROMISED AND TAKE OTHER STEPS IN ACCORDANCE WITH APPLICABLE LAWS OR REGULATIONS.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>SOME OF THE EXAMPLES OF THE DATA SECURITY CONTROLS IN PLACE AT BINGEMEEE (THIS IS NOT AN EXHAUSTIVE LIST):</span></li>
            <ol>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THE USE OF ENCRYPTION WHEN PERSONAL DATA IS TRANSFERRED TO BINGEMEEE’S SERVERS;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>LIMITED ACCESS TO PERSONAL DATA BY BINGEMEEE STAFF ON A NEED-TO-KNOW BASIS AND THE USE OF ROBUST AUTHENTICATION PROCESSES;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THE USE OF DATA CENTRES WITH EFFECTIVE PHYSICAL AND LOGICAL DATA SECURITY CONTROLS AND THE USE OF REPUTABLE THIRD PARTIES WHO HAVE DEMONSTRATED SECURITY CONSCIOUSNESS; AND</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>SECURE OFFICE PREMISES AND STAFF THAT ARE AWARE OF THEIR DATA PROTECTION RESPONSIBILITIES.</span></li>
            </ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOU ARE RESPONSIBLE FOR MAINTAINING THE SECRECY OF YOUR UNIQUE PASSWORD AND ACCOUNT INFORMATION, AND FOR CONTROLLING ACCESS TO EMAILS BETWEEN YOU AND BINGEMEEE, AT ALL TIMES.</span></li>
          </ol>
          <p><strong>YOUR CHOICES ABOUT YOUR INFORMATION:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE STRIVE TO PROVIDE YOU WITH CHOICES REGARDING THE PERSONAL INFORMATION YOU PROVIDE TO US. THIS SECTION DESCRIBES MECHANISMS WE PROVIDE FOR YOU TO CONTROL CERTAIN USES AND DISCLOSURES OF YOUR INFORMATION.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOU HAVE THE FOLLOWING RIGHTS, WHICH YOU CAN REQUEST FROM BINGEMEEE AT ANY TIME:</span></li>
            <ol>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>TO STOP PROCESSING YOUR PERSONAL INFORMATION ON A TEMPORARY BASIS;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THE RIGHT TO BE FORGOTTEN (DELETED FROM OUR SERVERS);</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THE RIGHT TO OBJECT TO PROCESSING; AND</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THE RIGHT TO ACCESS, CHANGE OR CORRECT YOUR PERSONAL INFORMATION.</span></li>
            </ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>EMAIL SUPPORT@BINGEMEEE.COM SHOULD YOU WISH TO EXERCISE ANY OF THE RIGHTS ABOVE.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>FOLLOWING TERMINATION OR DEACTIVATION OF YOUR ACCOUNT, BINGEMEEE OR ITS SERVICE PROVIDERS MAY RETAIN INFORMATION (INCLUDING YOUR PROFILE INFORMATION) AND YOUR CONTENT FOR A COMMERCIALLY REASONABLE TIME FOR BACKUP, ARCHIVAL, AND/OR AUDIT PURPOSES. UNLESS YOU CONTACT US TO DELETE YOUR PERSONAL INFORMATION, BINGEMEEE WILL ONLY RETAIN YOUR PERSONAL INFORMATION FOR THE PERIOD NECESSARY TO FULFIL THE PURPOSES OUTLINED IN THIS POLICY, BUT IN NO EVENT LONGER THAN 6 MONTHS, UNLESS A MORE EXTENDED RETENTION PERIOD IS REQUIRED BY LAW.</span></li>
          </ol>
          <p><strong>CHILDREN’S PRIVACY:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE DOES NOT KNOWINGLY COLLECT OR SOLICIT ANY INFORMATION FROM ANYONE UNDER THE AGE OF 18 OR KNOWINGLY ALLOW SUCH PERSONS TO REGISTER FOR THE SERVICE. THE SERVICE AND ITS CONTENT ARE NOT DIRECTED AT ANYONE UNDER THE AGE OF 18. IN THE EVENT THAT WE LEARN THAT WE HAVE COLLECTED PERSONAL INFORMATION FROM A CHILD UNDER AGE 18 WITHOUT PARENTAL CONSENT, WE WILL DELETE THAT INFORMATION AS QUICKLY AS POSSIBLE. IF YOU BELIEVE THAT WE MIGHT HAVE ANY INFORMATION FROM OR ABOUT A CHILD UNDER 18, PLEASE CONTACT US AT SUPPORT@BINGEMEEE.COM.</span></li>
          </ol>
          <p><strong>OTHER WEBSITES AND SERVICES:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WE ARE NOT RESPONSIBLE FOR THE PRACTICES EMPLOYED BY ANY WEBSITES OR SERVICES LINKED TO OR FROM OUR SERVICE, INCLUDING THE INFORMATION OR CONTENT CONTAINED WITHIN THEM. PLEASE REMEMBER THAT WHEN YOU USE A LINK TO GO FROM OUR SERVICE TO ANOTHER WEBSITE OR SERVICE, OUR PRIVACY POLICY DOES NOT APPLY TO THOSE THIRD-PARTY WEBSITES OR SERVICES. YOUR BROWSING AND INTERACTION ON ANY THIRD-PARTY WEBSITE OR SERVICE, INCLUDING THOSE WITH A LINK ON OUR WEBSITE, ARE SUBJECT TO THAT THIRD PARTY'S OWN RULES AND POLICIES. IN ADDITION, YOU AGREE THAT WE ARE NOT RESPONSIBLE AND DO NOT HAVE CONTROL OVER ANY THIRD PARTIES THAT YOU AUTHORISE TO ACCESS YOUR CONTENT. IF YOU ARE USING A THIRD-PARTY WEBSITE OR SERVICE AND ALLOW THEM TO ACCESS YOUR CONTENT, YOU DO SO AT YOUR OWN RISK.</span></li>
          </ol>
          <p><strong>THE EXISTENCE OF AUTOMATED DECISION-MAKING, INCLUDING PROFILING:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE DOES NOT TAKE ANY DECISIONS INVOLVING THE USE OF ALGORITHMS OR PROFILING THAT SIGNIFICANTLY AFFECTS YOU.</span></li>
          </ol>
          <p><strong>HOW TO CONTACT </strong><span style={{ fontWeight: 400 }}>BINGEMEEE</span><strong>:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF YOU HAVE ANY QUESTIONS ABOUT THIS PRIVACY POLICY OR THE SERVICE, PLEASE CONTACT OUR DATA PRIVACY OFFICER AT SUPPORT@BINGEMEEE.COM. EU RESIDENTS MAY ALSO EXERCISE THEIR DATA SUBJECT RIGHTS BY CONTACTING OUR DATA PRIVACY OFFICER.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF YOU ARE UNSATISFIED WITH THE REPLY YOU RECEIVE FROM BINGEMEEE, YOU MAY REFER YOUR COMPLAINT TO THE RELEVANT REGULATOR IN YOUR JURISDICTION. IF YOU ASK US, WE WILL ENDEAVOUR TO PROVIDE YOU WITH INFORMATION ABOUT RELEVANT COMPLAINT AVENUES WHICH MAY BE APPLICABLE TO YOUR CIRCUMSTANCES.</span></li>
          </ol>
          <p><strong>CHANGES TO OUR PRIVACY POLICY:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE MAY MODIFY OR UPDATE THIS PRIVACY POLICY FROM TIME TO TIME, SO PLEASE REVIEW IT PERIODICALLY. WE MAY PROVIDE YOU ADDITIONAL FORMS OF NOTICE OF MODIFICATIONS OR UPDATES AS APPROPRIATE UNDER THE CIRCUMSTANCES. YOUR CONTINUED USE OF BINGEMEEE OR THE SERVICE AFTER ANY MODIFICATION TO THIS PRIVACY POLICY WILL CONSTITUTE YOUR ACCEPTANCE OF SUCH MODIFICATION.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>IF AT ANY TIME IN THE FUTURE WE PLAN TO SHARE PERSONAL INFORMATION WITH MORE THIRD PARTIES, BINGEMEEE WILL MAINTAIN GDPR COMPLIANCE AND A HIGH STANDARD OF CARE FOR YOUR PERSONAL INFORMATION.</span></li>
          </ol>
          <p><strong>ADDITIONAL PRIVACY INFORMATION FOR RESIDENTS OF THE EUROPEAN ECONOMIC AREA:</strong></p>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>BINGEMEEE HAS TAKEN IMPORTANT STEPS FOR COMPLIANCE WITH THE GENERAL DATA PROTECTION REGULATION 2018 (GDPR) FOR EU USERS. AS A DATA CONTROLLER, BINGEMEEE UNDERSTANDS OUR OBLIGATIONS UNDER THE GDPR (EU) 2016/679 AND HAS TAKEN THE FOLLOWING STEPS:</span></li>
            <ol>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>REVISED THIS PRIVACY POLICY TO PROVIDE YOU WITH A CLEAR UNDERSTANDING OF OUR PRIVACY PRACTICES;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>APPOINTED A BINGEMEEE DATA PROTECTION OFFICER WHO CAN RESPOND TO EU DATA SUBJECTS AND DATA PROTECTION AUTHORITIES AS NEEDED;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>INTRODUCED NEW PRODUCT FEATURES AND FUNCTIONALITY TO ALLOW USERS BETTER CONTROL OVER THEIR PRIVACY;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>REVIEWED OUR DATA INVENTORY AND THIRD PARTY RELATIONSHIPS TO GAIN A COMPLETE PICTURE OF DATA FLOWS AND TAKE A PRIVACY BY DESIGN APPROACH TO OUR DATA HOLDINGS;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>ENHANCED OUR DATA SECURITY CONTROLS SUCH THAT REGARDLESS OF THE DATA FLOW, REASONABLE EFFORTS ARE MADE TO PROTECT OUR USER DATA AT ALL TIMES;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>DEVELOPED A PROCEDURE TO RESPOND TO ANY REQUESTS THAT MAY BE RECEIVED FROM USERS WHO ARE EU RESIDENTS REGARDING THEIR SUBJECT DATA RIGHTS;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>REVIEWED AND REVISED OUR DATA RETENTION RULES TO ENSURE BINGEMEEE IS NOT RETAINING PERSONAL INFORMATION THAT IS NO LONGER IN USE;</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>REQUIRED OUR THIRD PARTIES WHO WE ENTRUST WITH BINGEMEEE USER DATA TO COMMIT TO THE CONTINUED PROTECTION OF SUCH DATA AND COMPLY WITH THE GDPR RESPONSIBILITIES AS A DATA PROCESSOR; AND</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>INSTITUTED A PRIVACY DATA BREACH RESPONSE PLAN TO ENSURE ANY PRIVACY INCIDENTS ARE HANDLED EFFECTIVELY AND EFFICIENTLY.</span></li>
            </ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>CONTROLLER: BINGEMEEE (BARADIEL) IS A PARTNERSHIP COMPANY ESTABLISHED IN CHENNAI. OUR ADDRESS IS NO.62, MUNIAPPAN CHETTY STREET, PERAMBUR, CHENNAI - 600100 AND OUR CONTACT EMAIL ADDRESS IS SUPPORT@BINGEMEEE.COM. FOR THE PURPOSES OF THE GDPR, WE ARE THE DATA CONTROLLER.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>LEGAL BASIS: WE DESCRIBE IN THE SECTION ABOVE “HOW WE USE YOUR INFORMATION” THE PURPOSES FOR WHICH WE USE THE DATA COLLECTED AND SHARED. WHERE WE ARE USING THE DATA IN ORDER TO PROVIDE BINGEMEEE’S SERVICES TO YOU, OUR LEGAL BASIS FOR SUCH USE IS ON THE BASIS OF OUR CONTRACT WITH YOU. FOR ALL OTHER PURPOSES, OUR LEGAL BASIS IS OUR LEGITIMATE INTEREST IN RUNNING OUR BUSINESS, INCLUDING ENSURING BINGEMEEE’S SERVICE FUNCTIONS PROPERLY AND IMPROVING AND CREATING NEW PRODUCTS AND SERVICES EXCEPT WHERE WE OBTAIN YOUR CONSENT FOR PARTICULAR PROCESSING. IN THIS EVENT, THE LEGAL BASIS WILL BE YOUR CONSENT.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>YOUR RIGHTS: TO EXERCISE ANY OF THESE RIGHTS, PLEASE CONTACT US AT SUPPORT@BINGEMEEE.COM. PLEASE NOTE THAT THESE RIGHTS ARE LIMITED, FOR EXAMPLE, WHERE FULFILLING YOUR REQUEST WOULD ADVERSELY AFFECT OTHER INDIVIDUALS OR WHERE WE ARE REQUIRED BY LAW TO RETAIN YOUR PERSONAL DATA.</span></li>
            <ol>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>ACCESS AND PORTABILITY: YOU ARE ENTITLED TO REQUEST ACCESS TO THE PERSONAL INFORMATION WE HOLD AND BE PROVIDED WITH CERTAIN INFORMATION ABOUT HOW WE USE YOUR PERSONAL INFORMATION AND WHO WE SHARE IT WITH. YOU HAVE PROVIDED YOUR PERSONAL DATA TO US WITH YOUR CONSENT, YOU HAVE THE RIGHT TO ASK US FOR A COPY OF THIS DATA IN A STRUCTURED, MACHINE-READABLE FORMAT AND ASK US TO SHARE (PORT) THIS DATA WITH ANOTHER DATA CONTROLLER.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>CORRECTION: YOU HAVE THE RIGHT TO ASK US TO CORRECT YOUR PERSONAL DATA WHERE IT IS INACCURATE OR INCOMPLETE.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>RIGHT TO DELETION: IN CERTAIN CIRCUMSTANCES, YOU HAVE THE RIGHT TO ASK US TO DELETE THE PERSONAL DATA WE HOLD ABOUT YOU.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>RESTRICTION: IN CERTAIN CIRCUMSTANCES, YOU HAVE THE RIGHT TO ASK US TO RESTRICT (STOP ANY ACTIVE) PROCESSING OF YOUR PERSONAL DATA.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>OBJECTION: YOU CAN OBJECT TO OUR PROCESSING OF YOUR PERSONAL DATA BASED ON OUR LEGITIMATE INTERESTS, AND WE WILL NO LONGER PROCESS YOUR PERSONAL DATA UNLESS WE CAN DEMONSTRATE AN OVERRIDING LEGITIMATE GROUND.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>WITHDRAWAL OF CONSENT: IN THE EVENT WE HAVE RELIED UPON YOUR CONSENT TO PROCESS YOUR PERSONAL DATA, YOU MAY WITHDRAW CONSENT AT ANY TIME BY CONTACTING US AT SUPPORT@BINGEMEEE.COM.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>CEASE USE: FINALLY, YOU MAY PERMANENTLY, CEASE USING BINGEMEEE’S SERVICE, AND YOU MAY DEACTIVATE YOUR ACCOUNT. AFTER A REASONABLE TIME FOLLOWING SUCH DEACTIVATION, AS SET FORTH ABOVE, BINGEMEEE WOULD NO LONGER HAVE ACCESS TO YOUR PERSONAL INFORMATION.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>COMPLAINTS: IN THE EVENT THAT YOU WISH TO MAKE A COMPLAINT ABOUT HOW WE PROCESS YOUR PERSONAL DATA, PLEASE CONTACT US IN THE FIRST INSTANCE AT SUPPORT@BINGEMEEE.COM, AND WE WILL ENDEAVOUR TO DEAL WITH YOUR REQUEST AS SOON AS POSSIBLE. THIS IS WITHOUT PREJUDICE TO YOUR RIGHT TO RAISE A COMPLAINT WITH RELEVANT SUPERVISORY AUTHORITY.</span></li>
              <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>DISPUTE RESOLUTION PLATFORM: YOU MAY ALSO USE THE ONLINE DISPUTE RESOLUTION (ODR) PLATFORM TO RESOLVE THE DISPUTE WITH US. FOR MORE DETAILS, PLEASE VISIT THE WEBSITE ON THE ‘YOUR EUROPE’ PORTAL: BETTER BUSINESS BUREAU WEBSITE </span><a href="http://www.bbb.org/"><span style={{ fontWeight: 400 }}>HTTP://WWW.BBB.ORG</span></a></li>
            </ol>
          </ol>
          <p>&nbsp;</p>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default privacyPolicy;
