import React from "react";
import Footer from "../../src/components/footer";
import Header from "../../src/components/header";
import styles from "./broadcaster-agreement.module.scss";



const privacyPolicy = () => {
  return (
    <>
      <Header />
      <h1 className={styles.heading}>BROADCAST AGREEMENT</h1>
      <div className={styles.broadcast}>
        <div>
          <p><span style={{ fontWeight: 400 }}>PLEASE READ CAREFULLY THE FOLLOWING PROVISIONS OF THIS AGREEMENT.</span></p>
          <ol>
            <li><strong> SPECIAL NOTICES</strong></li>
          </ol>
          <p><span style={{ fontWeight: 400 }}>BARADIEL, COMPANY REGISTERED IN CHENNAI (THE “COMPANY”) AND ITS AFFILIATES, WELCOMES YOU TO </span><strong>BINGEMEEE.COM</strong><span style={{ fontWeight: 400 }}> (THE “WEBSITE”)(THE “WEBSITE”).</span></p>
          <p><span style={{ fontWeight: 400 }}>IT IS IMPORTANT TO THE COMPANY THAT YOU AND OTHER VISITORS HAVE THE BEST POSSIBLE EXPERIENCE WHILE USING THE WEBSITE, AND THAT, WHEN YOU USE THE WEBSITE, YOU UNDERSTAND YOUR LEGAL RIGHTS AND OBLIGATIONS.</span></p>
          <p><span style={{ fontWeight: 400 }}>PLEASE READ THIS AGREEMENT, WHICH GOVERNS YOUR USE OF THE WEBSITE, INCLUDING ANY CONTENT, FUNCTIONALITY, AND SERVICES OFFERED ON OR THROUGH THE WEBSITE. YOUR ACCESS TO THE WEBSITE IS ON THE CONDITION THAT YOU AGREE TO THIS AGREEMENT.</span></p>
          <p><span style={{ fontWeight: 400 }}>FOR THE PURPOSES OF THIS AGREEMENT, YOU AND BINGEMEEE WILL BE JOINTLY REFERRED TO AS THE “PARTIES” AND RESPECTIVELY AS A “PARTY”.</span></p>
          <p><span style={{ fontWeight: 400 }}>1.2 WHILE USING OUR BROADCASTING SERVICES, YOU ARE DEEMED TO BE OUR VENDOR AND MUST ABIDE BY ALL APPLICABLE LAWS AND REGULATIONS, AND BINGEMEEE COMMUNITY GUIDELINES, WHICH MAY BE UPDATED FROM TIME TO TIME AT OUR SOLE DISCRETION. BY CONTINUING TO PERFORM AS BROADCASTER, YOU AGREE TO BE BOUND BY THE REVISED AGREEMENT.</span></p>
          <p><span style={{ fontWeight: 400 }}>1.3 YOU MAY ONLY BE OUR BROADCASTER IF YOU ARE 18 YEARS OR OLDER, AND IF YOU ARE NOT SUBJECT TO STATUTORY AGE LIMITS TO ENTER INTO THIS AGREEMENT ACCORDING TO THE APPLICABLE LAWS AND REGULATIONS IN YOUR COUNTRY. YOU MAY NOT FALSELY CLAIM YOU HAVE REACHED THE MINIMUM AGE.</span></p>
          <p><span style={{ fontWeight: 400 }}>1.4 THESE TERMS SHALL BE READ IN CONJUNCTION WITH THE BINGEMEEE USER AGREEMENT. EXCEPT OTHERWISE PROVIDED, ALL CAPITALIZED TERMS SHALL HAVE THE SAME MEANING AS DEFINED IN THE BINGEMEEE USER AGREEMENT.</span></p>
          <ol start={2}>
            <li><strong> TERMS OF USE</strong></li>
          </ol>
          <p><span style={{ fontWeight: 400 }}>2.1 YOU ARE RESPONSIBLE FOR THE ACCURACY OF INFORMATION THAT YOU PROVIDE TO BINGEMEEE, AND UPON REQUEST FROM BINGEMEEE, YOU MUST VERIFY THE ACCURACY OF THE INFORMATION GIVEN.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.2 YOU MAY NOT CREATE BINGEMEEE ACCOUNTS FOR OTHERS, OR ALLOW OTHERS TO USE YOUR BINGEMEEE ACCOUNT. YOU SHALL IMMEDIATELY NOTIFY BINGEMEEE IF YOU DISCOVER UNLAWFUL USE OF YOUR ACCOUNT BY OTHERS.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.3 IN CONSIDERATION OF OUR BROADCASTING SERVICES, YOU AGREE THAT BINGEMEEE HAS THE RIGHT TO PLACE ADVERTISEMENTS OR OTHER TYPES OF COMMERCIAL INFORMATION, INCLUDING THE BINGEMEEE LOGO, IN THE STREAMING ROOM.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.4 WHILE USING OUR BROADCASTING SERVICES, YOU MUST ABIDE BY ALL APPLICABLE LAWS AND REGULATIONS, AND BINGEMEEE COMMUNITY GUIDELINES, WHICH MAY BE UPDATED FROM TIME TO TIME AT OUR SOLE DISCRETION.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5 YOU MAY ONLY SHARE INFORMATION THAT YOU ARE COMFORTABLE SHARING WITH THE PUBLIC. YOU MAY NOT DISTRIBUTE VIA BINGEMEEE ANY CONTENT THAT MAY BE CONSIDERED:</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.1 PORNOGRAPHIC, OBSCENE OR INDECENT, OR ANY ADULT CONTENT, INCLUDING ANY FORM OF CHILD EXPLOITATION;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.2 EXCESSIVELY VIOLENT, INCLUDING ANY CONTENT THAT IS RELATED TO DEATH OR SERIOUS INJURY;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.3 DEPICTING, ENCOURAGING OR ASSISTING SUICIDE OR SELF-HARM;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.4 RUMORS, FALSE OR MISLEADING INFORMATION;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.5 HATEFUL SPEECH OR CONDUCT, INCLUDING ANY CONTENT THAT PROMOTES RACISM, TERRORISM, AGEISM OR SEXISM;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.6 PROFANE, BLASPHEMOUS OR ANY CONTENT THAT MAY OFFEND PEOPLE OF CERTAIN FAITH, OR OTHERWISE RELATED TO RELIGION;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.7 RELATED TO GAMBLING, ABORTION, WEAPON, OR OTHER HIGHLY EXPLOSIVE SUBJECT MATTER;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.8 ABUSIVE, LIBELOUS, OR OTHERWISE HARASSING OTHER PEOPLE OR GROUP;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.9 SPAM, JUNK MAIL OR OTHER UNSOLICITED ADVERTISEMENT;</span></p>
          <p><span style={{ fontWeight: 400 }}>2.5.10 OTHER CONTENT THAT IN THE JUDGEMENT OF BINGEMEEE ARE NEGATIVE CONTENTS OR OTHERWISE NOT SUITABLE FOR DISTRIBUTION.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.6 YOU MAY NOT IMPERSONATE ANY OTHER INDIVIDUAL, ENTITY, GOVERNMENTAL AGENCY OR ORGANIZATIONS.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.7 YOU MAY NOT PUBLISH OR DISTRIBUTE OTHER PEOPLE'S PRIVATE INFORMATION WITHOUT THEIR EXPRESS AUTHORIZATION AND PERMISSION.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.8 YOU AFFIRM, REPRESENT, AND WARRANT THAT YOU OWN OR HAVE THE NECESSARY LICENSES, RIGHTS, CONSENTS, AND PERMISSIONS TO PUBLISH OR DISTRIBUTE ANY COPYRIGHTED OR PROPRIETARY WORKS. YOU ARE SOLELY RESPONSIBLE FOR OBTAINING SUCH LICENSES, RIGHTS, CONSENTS, AND PERMISSIONS.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.9 YOU MAY NOT PUBLISH OR LINK TO ANY MALICIOUS CODE, PHISHING WEBSITE OR OTHER CONTENT THAT MAY THREATEN THE SECURITY OF THE INTERNET.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.10 BINGEMEEE HAS THE RIGHT TO REVIEW AND MONITOR YOUR BROADCASTING ON BINGEMEEE. BINGEMEEE WILL EVALUATE YOUR PERFORMANCE AND GIVE REWARDS BASED ON VARIOUS FACTORS INCLUDING STREAMING TIME, COMPLIANT ISSUES, REWARDED VIRTUAL GIFTS, ETC. BINGEMEEE SHALL HAVE THE RIGHT TO COMMENT AND MAKE SUGGESTIONS ABOUT THE PERFORMANCE CONTENT AND YOU AGREE TO MAKE ADJUSTMENTS ACCORDINGLY IN THREE DAYS.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.11 IF BINGEMEEE, AT ITS SOLE DISCRETION, REASONABLY BELIEVES THAT YOU HAVE VIOLATED THE BINGEMEEE BROADCASTING AGREEMENT, BINGEMEEE MAY FREEZE, SUSPEND, DISABLE, BAN OR REVOKE YOUR ACCOUNT. YOU UNDERSTAND THAT ANY VIRTUAL GIFT ASSOCIATED WITH YOUR ACCOUNT WILL BE FROZEN, SUSPENDED, DISABLED, BANNED OR REVOKED AS WELL.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.12 IF BINGEMEEE DISCOVERS OR REASONABLY SUSPECTS THAT ANY OF YOUR VIRTUAL GIFT IS ACQUIRED IN A FRAUDULENT OR ILLEGAL MANNER, OR IS IN AN ABNORMAL STATUS, BINGEMEEE MAY FREEZE, SUSPEND, DISABLE, BAN OR REVOKE SUCH VIRTUAL GIFT.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.13 IF YOUR ACCOUNT IS FROZEN, SUSPENDED, DISABLED, BANNED OR REVOKED, YOU MAY NOT CREATE A SECOND ACCOUNT OR ASK ANY OTHER PERSON TO CREATE A SECOND ACCOUNT FOR YOU.</span></p>
          <p><span style={{ fontWeight: 400 }}>2.14 IF YOU VIOLATE ANY TERMS OF USE, YOU SHALL INDEMNIFY AND HOLD HARMLESS OF BINGEMEEE AGAINST ANY LIABILITY RESULTING FROM A CLAIM BY A THIRD PARTY IN RELATION TO YOUR VIOLATION.</span></p>
          <ol start={3}>
            <li><strong> INTELLECTUAL PROPERTY RIGHTS</strong></li>
          </ol>
          <p><span style={{ fontWeight: 400 }}>3.1 ALL TEXT, DATA, IMAGES, GRAPHICS, AUDIO AND/OR VIDEO INFORMATION AND OTHER MATERIALS WITHIN THE BROADCASTING SERVICES PROVIDED BY BINGEMEEE ARE PROPERTY OF BINGEMEEE AND ARE PROTECTED BY COPYRIGHT, TRADEMARK AND/OR OTHER PROPERTY RIGHTS LAWS. NOTHING IN THIS AGREEMENT SHALL BE CONSTRUED AS CONFERRING ANY LICENSE OF ANY INTELLECTUAL PROPERTY RIGHTS OR SUCH MATERIALS BY BINGEMEEE TO YOU.</span></p>
          <p><span style={{ fontWeight: 400 }}>3.2 BY USING AND/OR UPLOADING ANY LIVE STREAM CONTENT OR OTHER CONTENT THROUGH BROADCASTING SERVICES TO PUBLICLY ACCESSIBLE AREAS OF BINGEMEEE WEBSITE, YOU GRANT TO BINGEMEEE AND ITS SUB-LICENSEES THE PERMISSION, FREE, PERMANENT, IRREVOCABLE, NON-EXCLUSIVE AND FULLY SUB-LICENSABLE RIGHTS AND LICENSE, WITHOUT ANY TERRITORIAL OR TIME LIMITATIONS AND WITHOUT REQUIRING ANY APPROVALS AND/OR COMPENSATIONS, TO USE, COPY, MODIFY, ADAPT, PUBLISH, TRANSLATE, EDIT, DISPOSE, CREATE DERIVATIVE WORKS OF, DISTRIBUTE, PERFORM AND PUBLICLY DISPLAY SUCH CONTENT (IN WHOLE OR IN PART), AND/OR INCORPORATE SUCH CONTENT INTO EXISTING OR FUTURE FORMS OF WORK, MEDIA OR TECHNOLOGY.</span></p>
          <ol start={4}>
            <li><strong> DISCLAIMERS</strong></li>
          </ol>
          <p><span style={{ fontWeight: 400 }}>4.1 YOU SHALL BE FULLY RESPONSIBLE FOR ANY RISKS INVOLVED IN USING BROADCASTING SERVICES. ANY USE OR RELIANCE ON BROADCASTING SERVICES WILL BE AT YOUR OWN RISK.</span></p>
          <p><span style={{ fontWeight: 400 }}>4.2 UNDER NO CIRCUMSTANCE DOES BINGEMEEE GUARANTEE THAT THE BROADCASTING SERVICES WILL SATISFY YOUR REQUIREMENTS, OR GUARANTEE THAT THE BROADCASTING SERVICES WILL BE UNINTERRUPTED. THE TIMELINESS, SECURITY AND ACCURACY OF THE BROADCASTING SERVICES ARE ALSO NOT GUARANTEED. YOU ACKNOWLEDGE AND AGREE THAT THE BROADCASTING SERVICES IS PROVIDED BY BINGEMEEE ON AN “AS IS” BASIS. BINGEMEEE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND EXPRESS OR IMPLIED AS TO THE OPERATION AND THE PROVIDING OF SUCH BROADCASTING SERVICES OR ANY PART THEREOF. BINGEMEEE SHALL NOT BE LIABLE IN ANY WAY FOR THE QUALITY, TIMELINESS, ACCURACY OR COMPLETENESS OF THE BROADCASTING SERVICES AND SHALL NOT BE RESPONSIBLE FOR ANY CONSEQUENCES WHICH MAY ARISE FROM YOUR USE OF SUCH BROADCASTING SERVICES.</span></p>
          <p><span style={{ fontWeight: 400 }}>4.3 BINGEMEEE DOES NOT GUARANTEE THE ACCURACY AND LEGALITY OF ANY EXTERNAL LINKS THAT MAY BE ACCESSIBLE BY USING THE BROADCASTING SERVICES AND/OR ANY EXTERNAL LINKS THAT HAVE BEEN PLACED FOR YOUR REFERENCE ONLY. BINGEMEEE SHALL NOT BE RESPONSIBLE FOR THE CONTENT OF ANY LINKED SITE OR ANY LINK CONTAINED IN A LINKED SITE, AND BINGEMEEE SHALL NOT BE HELD RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE IN CONNECTION WITH THE USE OF THE SERVICES BY YOU. MOREOVER, BINGEMEEE SHALL NOT BEAR ANY RESPONSIBILITY FOR THE CONTENT OF ANY WEBPAGE THAT YOU ARE DIRECTED TO VIA AN EXTERNAL LINK THAT IS NOT UNDER THE CONTROL OF BINGEMEEE.</span></p>
          <p><span style={{ fontWeight: 400 }}>4.4 BINGEMEEE SHALL NOT BEAR ANY LIABILITY FOR THE INTERRUPTION OF OR OTHER INADEQUACIES IN THE SERVICES CAUSED BY CIRCUMSTANCES OF FORCE MAJEURE, OR THAT ARE OTHERWISE BEYOND THE CONTROL OF BINGEMEEE. HOWEVER, AS FAR AS POSSIBLE, BINGEMEEE SHALL REASONABLY ATTEMPT TO MINIMIZE THE RESULTING LOSSES OF AND IMPACT UPON YOU.</span></p>
          <ol start={5}>
            <li><strong> LEGAL JURISDICTION</strong></li>
          </ol>
          <ol>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>THIS AGREEMENT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF ENGLAND, WITHOUT REGARD TO CHOICE OF LAW PRINCIPLES.</span></li>
            <li style={{ fontWeight: 400 }}><span style={{ fontWeight: 400 }}>EXCEPT FOR DISPUTES SUBJECT TO ARBITRATION, ALL DISPUTES ARISING OUT OF OR RELATING TO THE WEBSITE OR THIS AGREEMENT WILL BE SUBJECT TO THE EXCLUSIVE JURISDICTION AND VENUE OF THE COURTS OF COMPETENT JURISDICTION LOCATED IN ENGLAND. EACH PARTY HEREBY SUBMITS TO THE PERSONAL JURISDICTION OF THE COURTS OF COMPETENT JURISDICTION LOCATED IN ENGLAND TO RESOLVE ALL DISPUTES NOT SUBJECT TO ARBITRATION. EACH PARTY HEREBY WAIVES ANY RIGHT TO SEEK ANOTHER FORUM OR VENUE BECAUSE OF IMPROPER OR INCONVENIENT FORUM.</span></li>
          </ol>
          <ol start={6}>
            <li><strong> OTHER TERMS</strong></li>
          </ol>
          <p><span style={{ fontWeight: 400 }}>6.1 OTHER THAN AS STIPULATED BY THIS AGREEMENT, NO OTHER RIGHTS ARE VESTED IN EITHER PARTY TO THIS AGREEMENT.</span></p>
          <p><span style={{ fontWeight: 400 }}>6.2 IF ANY PROVISION OF THIS AGREEMENT IS RENDERED VOID OR UNENFORCEABLE BY COMPETENT AUTHORITIES, IN WHOLE OR IN PART, FOR ANY REASON, THE REMAINING PROVISIONS OF THIS AGREEMENT SHALL REMAIN VALID AND BINDING.</span></p>
          <p><span style={{ fontWeight: 400 }}>6.3 THE HEADINGS WITHIN THIS AGREEMENT HAVE BEEN SET FOR THE SAKE OF CONVENIENCE, AND SHALL BE DISREGARDED IN THE INTERPRETATION OF THIS AGREEMENT.</span></p>
          <p><br /><br /></p>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default privacyPolicy;
